[tox]
envlist =
    py{310,311,312,313}-dj52-wagtail70
    py{310,311,312,313,314}-dj52-wagtail{73,74}
    py{312,313,314}-dj60-wagtail{73,74}
    flake8
    isort
    black

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
use_frozen_constraints = true
constrain_package_deps = true
usedevelop = True
setenv =
    PYTHONPATH = {toxinidir}
    DJANGO_SETTINGS_MODULE = wagtail_storages.tests.settings
deps =
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1
    wagtail70: wagtail>=7.0,<7.1
    wagtail73: wagtail>=7.3,<7.4
    wagtail74: wagtail>=7.4,<7.5
    wagtailmain: git+https://github.com/wagtail/wagtail.git@main#egg=Wagtail

commands =
    coverage run --source="{toxinidir}/wagtail_storages" -m django test {posargs:wagtail_storages}
    django-admin check
    django-admin makemigrations --check --noinput
    coverage report -m --omit="{toxinidir}/wagtail_storages/tests/*" --fail-under=80
extras = testing

[testenv:black]
basepython = python3
commands =
    black --check ./

[testenv:flake8]
basepython = python3
commands =
    flake8 wagtail_storages

[testenv:isort]
basepython = python3
changedir = {toxinidir}
commands =
    isort --check-only --diff wagtail_storages
